[theme]
primaryColor = "#FF9933"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = false
